openapi: 3.1.0
info:
  title: Interzoid Company Name Matching API
  description: >
    This API uses AI models, machine learning, specialized algorithms, and
    extensive knowledge bases to generate a similarity key for a company or
    organization name…
  version: 1.0.0
  termsOfService: https://www.interzoid.com/api-terms-use
  contact:
    name: Interzoid Support
    url: https://www.interzoid.com
    email: support@interzoid.com

externalDocs:
  description: Company Name Matching API home page and documentation
  url: https://www.interzoid.com/apis/company-name-matching

servers:
  - url: https://api.interzoid.com
    description: Production server

tags:
  - name: Company Name Similarity Key
    description: >
      Generate similarity keys to identify inconsistent…
paths:
  /getcompanymatchadvanced:
    get:
      operationId: getCompanyMatchAdvanced
      tags:
        - Company Name Similarity Key
      summary: Generate similarity key for a company or organization name
      parameters:
        - name: company
          in: query
          required: true
          schema:
            type: string
        - name: algorithm
          in: query
          required: true
          schema:
            type: string
            enum:
              - wide
              - narrow
              - model-v4-wide
              - model-v4-narrow
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyMatchResponse'

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
    apiKeyQuery:
      type: apiKey
      in: query
      name: license

  schemas:
    CompanyMatchResponse:
      type: object
      required:
        - SimKey
        - Code
      properties:
        SimKey:
          type: string
        Credits:
          type: string    # <— UPDATED TO STRING
        Code:
          type: string

security:
  - apiKeyHeader: []
  - apiKeyQuery: []
